### ISSUE TITLE
circuit diagram 

### ISSUE THREAD

**Issue by jcdesignweb** [rpakdel/arduino-esp8266-nrf24-door#1]
Hi Réza, Is interesting for me this project!, I would like to know something more about it. I am trying to do some similar using a Wemos Mini d1 as ESP module for my circuits and I need use an nrf24l01 to make and rf connection between an Arduino nano & My Arduino Wemos. I was seeing this project but I couldn't found the diagram to see how you connected Wemos pins with the nrf24l01.. 

Thank you Very much!
Cheers!

**Comment by rpakdel** [comment]
The nrf24l01 uses SPI to connect to the microcontroller. 

I suggest you review the pin connections on the Wemos D1: 

https://i2.wp.com/randomnerdtutorials.com/wp-content/uploads/2019/05/ESP8266-WeMos-D1-Mini-pinout-gpio-pin.png?ssl=1

And the nrf24l01 pins

https://components101.com/wireless/nrf24l01-pinout-features-datasheet

Connect MOSI, MISO and SCK(L) pins together. You can use any pins for CE and CSN since they can be configured in the library. Keep in mind pin 0 and pin 2 have special function and are more complicated to use.

Hope this helps

**Comment by jcdesignweb** [comment]
Thank's !! It was very helpful!
